config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :ratings
  resources :user_identifications
  root 'react#home'
  resources :items

  devise_for :user, only: []

  # for facebook & twitter login
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' },
                     skip: [:invitations, :session, :registration],
                     path: ''

  namespace :auth, defaults: { format: :json } do
    get 'login'    => 'sessions#login' 
    post 'register' => 'sessions#register'
  end

end

app/models/user_identification.rb
class UserIdentification < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user
end

app/controllers/user_identifications_controller.rb
class UserIdentificationsController < ApplicationController
  before_action :set_user_identification, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @user_identifications = UserIdentification.all
    respond_with(@user_identifications)
  end

  def show
    respond_with(@user_identification)
  end

  def new
    @user_identification = UserIdentification.new
    respond_with(@user_identification)
  end

  def edit
  end

  def create
    @user_identification = UserIdentification.new(user_identification_params)
    @user_identification.save
    respond_with(@user_identification)
  end

  def update
    @user_identification.update(user_identification_params)
    respond_with(@user_identification)
  end

  def destroy
    @user_identification.destroy
    respond_with(@user_identification)
  end

  private
    def set_user_identification
      @user_identification = UserIdentification.find(params[:id])
    end

    def user_identification_params
      params.require(:user_identification).permit(:type, :code, :imgpath, :user_id)
    end
end

app/helpers/user_identifications_helper.rb
module UserIdentificationsHelper
end

app/views/user_identifications/_form.html.erb
<%= form_for(@user_identification) do |f| %>
  <% if @user_identification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_identification.errors.count, "error") %> prohibited this user_identification from being saved:</h2>

      <ul>
      <% @user_identification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :imgpath %><br>
    <%= f.text_field :imgpath %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_identifications/edit.html.erb
<h1>Editing User Identification</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_identification %> |
<%= link_to 'Back', user_identifications_path %>

app/views/user_identifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Identifications</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Code</th>
      <th>Imgpath</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_identifications.each do |user_identification| %>
      <tr>
        <td><%= user_identification.type %></td>
        <td><%= user_identification.code %></td>
        <td><%= user_identification.imgpath %></td>
        <td><%= user_identification.user %></td>
        <td><%= link_to 'Show', user_identification %></td>
        <td><%= link_to 'Edit', edit_user_identification_path(user_identification) %></td>
        <td><%= link_to 'Destroy', user_identification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User identification', new_user_identification_path %>

app/views/user_identifications/new.html.erb
<h1>New User Identification</h1>

<%= render 'form' %>

<%= link_to 'Back', user_identifications_path %>

app/views/user_identifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @user_identification.type %>
</p>

<p>
  <strong>Code:</strong>
  <%= @user_identification.code %>
</p>

<p>
  <strong>Imgpath:</strong>
  <%= @user_identification.imgpath %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_identification.user %>
</p>

<%= link_to 'Edit', edit_user_identification_path(@user_identification) %> |
<%= link_to 'Back', user_identifications_path %>