config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :ratings
  resources :user_identifications
  root 'react#home'
  resources :items

  devise_for :user, only: []

  # for facebook & twitter login
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' },
                     skip: [:invitations, :session, :registration],
                     path: ''

  namespace :auth, defaults: { format: :json } do
    get 'login'    => 'sessions#login' 
    post 'register' => 'sessions#register'
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @transactions = Transaction.all
    respond_with(@transactions)
  end

  def show
    respond_with(@transaction)
  end

  def new
    @transaction = Transaction.new
    respond_with(@transaction)
  end

  def edit
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.save
    respond_with(@transaction)
  end

  def update
    @transaction.update(transaction_params)
    respond_with(@transaction)
  end

  def destroy
    @transaction.destroy
    respond_with(@transaction)
  end

  private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(:fromUser_id, :toUser_id, :fromDate, :toDate, :price)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fromUser_id %><br>
    <%= f.text_field :fromUser_id %>
  </div>
  <div class="field">
    <%= f.label :toUser_id %><br>
    <%= f.text_field :toUser_id %>
  </div>
  <div class="field">
    <%= f.label :fromDate %><br>
    <%= f.datetime_select :fromDate %>
  </div>
  <div class="field">
    <%= f.label :toDate %><br>
    <%= f.datetime_select :toDate %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Fromuser</th>
      <th>Touser</th>
      <th>Fromdate</th>
      <th>Todate</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.fromUser %></td>
        <td><%= transaction.toUser %></td>
        <td><%= transaction.fromDate %></td>
        <td><%= transaction.toDate %></td>
        <td><%= transaction.price %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fromuser:</strong>
  <%= @transaction.fromUser %>
</p>

<p>
  <strong>Touser:</strong>
  <%= @transaction.toUser %>
</p>

<p>
  <strong>Fromdate:</strong>
  <%= @transaction.fromDate %>
</p>

<p>
  <strong>Todate:</strong>
  <%= @transaction.toDate %>
</p>

<p>
  <strong>Price:</strong>
  <%= @transaction.price %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>